adding polarisdb version 0.0.744, polaris version 0.0.4810, reporting version 0.0.1234

diff --git a/polarisdb/0.0.744/polarisdb_base.yaml b/polarisdb/0.0.744/polarisdb_base.yaml
--- a/polarisdb/0.0.744/polarisdb_base.yaml
+++ b/polarisdb/0.0.744/polarisdb_base.yaml
@@ -428,6 +428,38 @@ subjects:
 ---
 apiVersion: v1
 data:
+  init.sh: |-
+    #!/bin/bash
+    set -e
+    if [[ -z "$POSTGRES_HOST" ]]; then
+      echo "POSTGRES_HOST must be set"
+      exit 1
+    fi
+    if [[ `PGPASSWORD=${POSTGRES_PASSWORD} psql -h $POSTGRES_HOST -U $POSTGRES_USER -c "SELECT datname FROM pg_catalog.pg_database WHERE datname='cos';" --tuples-only | wc -l` -eq 1 ]]; then
+      echo "cos is missing. Initializing the database..."
+      PGPASSWORD=${POSTGRES_PASSWORD} psql -h $POSTGRES_HOST -U postgres << EOF
+      CREATE DATABASE cos;
+      CREATE DATABASE "jobs-service";
+      CREATE DATABASE issues;
+      CREATE DATABASE code_analysis;
+      CREATE DATABASE tds_fuzz;
+      CREATE DATABASE configs;
+      CREATE DATABASE triage_query;
+      CREATE DATABASE triage_command;
+      CREATE DATABASE desktop_metrics;
+      CREATE DATABASE tds_csv;
+      CREATE DATABASE tds_seeker;
+    EOF
+    fi
+kind: ConfigMap
+metadata:
+  labels:
+    name: polaris-postgres-init-config
+  name: polaris-postgres-init-config
+  namespace: ${NAMESPACE}
+---
+apiVersion: v1
+data:
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   POSTGRES_USER: ${POSTGRES_USERNAME}
 kind: ConfigMap
@@ -535,7 +567,7 @@ type: Opaque
 ---
 apiVersion: v1
 data:
-  gossip-key: WkxVaHBvUDNYckVZYUxrRThKSjkzOWNi
+  gossip-key: U3hvUEtWUWVkbjJwYVN6M1BrcjJtRHda
 kind: Secret
 metadata:
   labels:
@@ -1564,6 +1596,50 @@ spec:
 apiVersion: batch/v1
 kind: Job
 metadata:
+  labels:
+    name: polaris-init-postgres
+  name: polaris-init-postgres
+  namespace: ${NAMESPACE}
+spec:
+  backoffLimit: 4
+  template:
+    spec:
+      containers:
+      - args:
+        - -c
+        - sleep 60; /tmp/postgres-init/init.sh
+        command:
+        - /bin/bash
+        env:
+        - name: POSTGRES_HOST
+          value: ${POSTGRES_HOST}
+        - name: POSTGRES_PORT
+          value: ${POSTGRES_PORT}
+        - name: POSTGRES_USER
+          valueFrom:
+            configMapKeyRef:
+              key: POSTGRES_USER
+              name: postgresql-config
+        - name: POSTGRES_PASSWORD
+          valueFrom:
+            configMapKeyRef:
+              key: POSTGRES_PASSWORD
+              name: postgresql-config
+        image: registry.access.redhat.com/rhscl/postgresql-96-rhel7:1
+        name: postgres-init
+        volumeMounts:
+        - mountPath: /tmp/postgres-init
+          name: postgres-init
+      restartPolicy: Never
+      volumes:
+      - configMap:
+          defaultMode: 511
+          name: polaris-postgres-init-config
+        name: postgres-init
+---
+apiVersion: batch/v1
+kind: Job
+metadata:
   annotations:
     helm.sh/hook: pre-upgrade,pre-install
     helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
@@ -1754,7 +1830,7 @@ kind: Pod
 metadata:
   annotations:
     helm.sh/hook: test-success
-  name: swip-db-ui-test-qj1sb
+  name: swip-db-ui-test-ep1fk
   namespace: ${NAMESPACE}
 spec:
   containers:
