Added   polarisdb version = 0.0.749

diff --git a/polarisdb/0.0.749/polarisdb_base.yaml b/polarisdb/0.0.749/polarisdb_base.yaml
--- a/polarisdb/0.0.749/polarisdb_base.yaml
+++ b/polarisdb/0.0.749/polarisdb_base.yaml
@@ -268,6 +268,44 @@ subjects:
 ---
 apiVersion: v1
 data:
+  run.sh: |-
+    @test "Testing Consul cluster has quorum" {
+      for i in {0..2}; do
+        for n in {1..30}; do
+          if [ `kubectl exec polaris-db-consul-$i consul members --namespace=default | grep server | wc -l` -ge "3" ]; then
+            echo "polaris-db-consul-$i OK. consul members returning at least 3 records."
+            break
+          else
+            echo "polaris-db-consul-$i ERROR. consul members returning less than 3 records."
+          fi
+
+          if [ "$n" -ge "30" ]; then
+            echo "Failed $n times to get members from polaris-db-consul-$i"
+            exit 1
+          fi
+          sleep 10
+        done
+      done
+    }
+kind: ConfigMap
+metadata:
+  name: polaris-db-consul-tests
+  namespace: ${NAMESPACE}
+---
+apiVersion: v1
+data:
+  config.json: |
+    {"listener":{"tcp":{"address":"[::]:8200","cluster_address":"[::]:8201","tls_cert_file":"/vault/tls/tls.crt","tls_cipher_suites":"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA","tls_disable":false,"tls_key_file":"/vault/tls/tls.key","tls_prefer_server_cipher_suites":true}},"storage":{"consul":{"address":"polaris-db-consul:8500","path":"vault"}},"ui":true}
+kind: ConfigMap
+metadata:
+  labels:
+    app: polaris-db-vault
+    release: swip-db
+  name: polaris-db-vault-config
+  namespace: ${NAMESPACE}
+---
+apiVersion: v1
+data:
   init.sh: |-
     #!/bin/bash
     set -e
@@ -308,44 +346,6 @@ metadata:
   labels:
     app: postgresql
   name: postgresql-config
-  namespace: ${NAMESPACE}
----
-apiVersion: v1
-data:
-  run.sh: |-
-    @test "Testing Consul cluster has quorum" {
-      for i in {0..2}; do
-        for n in {1..30}; do
-          if [ `kubectl exec swip-db-consul-$i consul members --namespace=default | grep server | wc -l` -ge "3" ]; then
-            echo "swip-db-consul-$i OK. consul members returning at least 3 records."
-            break
-          else
-            echo "swip-db-consul-$i ERROR. consul members returning less than 3 records."
-          fi
-
-          if [ "$n" -ge "30" ]; then
-            echo "Failed $n times to get members from swip-db-consul-$i"
-            exit 1
-          fi
-          sleep 10
-        done
-      done
-    }
-kind: ConfigMap
-metadata:
-  name: swip-db-consul-tests
-  namespace: ${NAMESPACE}
----
-apiVersion: v1
-data:
-  config.json: |
-    {"listener":{"tcp":{"address":"[::]:8200","cluster_address":"[::]:8201","tls_cert_file":"/vault/tls/tls.crt","tls_cipher_suites":"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA","tls_disable":false,"tls_key_file":"/vault/tls/tls.key","tls_prefer_server_cipher_suites":true}},"storage":{"consul":{"address":"polaris-db-consul:8500","path":"vault"}},"ui":true}
-kind: ConfigMap
-metadata:
-  labels:
-    app: vault
-    release: swip-db
-  name: swip-db-vault-config
   namespace: ${NAMESPACE}
 ---
 apiVersion: v1
@@ -396,6 +396,18 @@ metadata:
 ---
 apiVersion: v1
 data:
+  gossip-key: SXErN2o1QVo0cm1ocXFNbG1OLzFCdz09
+kind: Secret
+metadata:
+  labels:
+    component: swip-db-consul
+    release: swip-db
+  name: polaris-db-consul-gossip-key
+  namespace: ${NAMESPACE}
+type: Opaque
+---
+apiVersion: v1
+data:
   host: ${SMTP_HOST}
   passwd: ${SMTP_PASSWORD}
   port: ${SMTP_PORT}
@@ -403,18 +415,6 @@ data:
 kind: Secret
 metadata:
   name: smtp
-  namespace: ${NAMESPACE}
-type: Opaque
----
-apiVersion: v1
-data:
-  gossip-key: STY3cUpJeFU1T01GbWFCeHlURElQcWpZ
-kind: Secret
-metadata:
-  labels:
-    component: swip-db-consul
-    release: swip-db
-  name: swip-db-consul-gossip-key
   namespace: ${NAMESPACE}
 type: Opaque
 ---
@@ -469,28 +469,12 @@ spec:
 apiVersion: v1
 kind: Service
 metadata:
-  labels:
-    app: postgresql
-  name: postgresql
-  namespace: ${NAMESPACE}
-spec:
-  ports:
-  - name: postgresql
-    port: 5432
-    protocol: TCP
-    targetPort: 5432
-  selector:
-    app: postgresql
----
-apiVersion: v1
-kind: Service
-metadata:
   annotations:
     service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
   labels:
     component: swip-db-consul
     release: swip-db
-  name: swip-db-consul
+  name: polaris-db-consul
   namespace: ${NAMESPACE}
 spec:
   clusterIP: None
@@ -527,7 +511,7 @@ metadata:
   labels:
     component: swip-db-consul
     release: swip-db
-  name: swip-db-consul-ui
+  name: polaris-db-consul-ui
   namespace: ${NAMESPACE}
 spec:
   ports:
@@ -541,9 +525,9 @@ apiVersion: v1
 kind: Service
 metadata:
   labels:
-    app: vault
+    app: polaris-db-vault
     release: swip-db
-  name: swip-db-vault
+  name: polaris-db-vault
   namespace: ${NAMESPACE}
 spec:
   ports:
@@ -552,9 +536,25 @@ spec:
     protocol: TCP
     targetPort: 8200
   selector:
-    app: vault
+    app: polaris-db-vault
     release: swip-db
   type: ClusterIP
+---
+apiVersion: v1
+kind: Service
+metadata:
+  labels:
+    app: postgresql
+  name: postgresql
+  namespace: ${NAMESPACE}
+spec:
+  ports:
+  - name: postgresql
+    port: 5432
+    protocol: TCP
+    targetPort: 5432
+  selector:
+    app: postgresql
 ---
 apiVersion: v1
 kind: Service
@@ -631,7 +631,7 @@ spec:
         - vault-init
         env:
         - name: VAULT_ADDR
-          value: https://swip-db-vault:8200
+          value: https://polaris-db-vault:8200
         - name: VAULT_CACERT
           value: /vault/tls/ca.crt
         - name: VAULT_INIT_SECRET
@@ -757,48 +757,14 @@ spec:
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
-  name: postgresql
+  annotations: {}
+  labels:
+    app: polaris-db-vault
+    release: swip-db
+  name: polaris-db-vault
   namespace: ${NAMESPACE}
 spec:
   replicas: 1
-  selector:
-    matchLabels:
-      app: postgresql
-  template:
-    metadata:
-      labels:
-        app: postgresql
-      name: postgresql
-    spec:
-      containers:
-      - envFrom:
-        - configMapRef:
-            name: postgresql-config
-        image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:1
-        imagePullPolicy: IfNotPresent
-        name: postgresql
-        ports:
-        - containerPort: 5432
-        volumeMounts:
-        - mountPath: /var/lib/postgresql/data
-          name: postgresdb
-          subPath: postgres
-      volumes:
-      - name: postgresdb
-        persistentVolumeClaim:
-          claimName: postgresql-pv-claim
----
-apiVersion: extensions/v1beta1
-kind: Deployment
-metadata:
-  annotations: {}
-  labels:
-    app: vault
-    release: swip-db
-  name: swip-db-vault
-  namespace: ${NAMESPACE}
-spec:
-  replicas: 3
   strategy:
     rollingUpdate:
       maxUnavailable: 1
@@ -807,7 +773,7 @@ spec:
     metadata:
       annotations: {}
       labels:
-        app: vault
+        app: polaris-db-vault
         release: swip-db
     spec:
       affinity:
@@ -816,7 +782,7 @@ spec:
           - podAffinityTerm:
               labelSelector:
                 matchLabels:
-                  app: swip-db-vault
+                  app: polaris-db-vault
                   release: swip-db
               topologyKey: kubernetes.io/hostname
             weight: 100
@@ -905,9 +871,11 @@ spec:
         volumeMounts:
         - mountPath: /vault/tls
           name: vault-tls-certificate
+      imagePullSecrets:
+      - name: gcr-json-key
       volumes:
       - configMap:
-          name: swip-db-vault-config
+          name: polaris-db-vault-config
         name: vault-config
       - emptyDir: {}
         name: vault-root
@@ -917,6 +885,40 @@ spec:
       - name: vault-init-secret
         secret:
           secretName: vault-init-secret
+---
+apiVersion: extensions/v1beta1
+kind: Deployment
+metadata:
+  name: postgresql
+  namespace: ${NAMESPACE}
+spec:
+  replicas: 1
+  selector:
+    matchLabels:
+      app: postgresql
+  template:
+    metadata:
+      labels:
+        app: postgresql
+      name: postgresql
+    spec:
+      containers:
+      - envFrom:
+        - configMapRef:
+            name: postgresql-config
+        image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:1
+        imagePullPolicy: IfNotPresent
+        name: postgresql
+        ports:
+        - containerPort: 5432
+        volumeMounts:
+        - mountPath: /var/lib/postgresql/data
+          name: postgresdb
+          subPath: postgres
+      volumes:
+      - name: postgresdb
+        persistentVolumeClaim:
+          claimName: postgresql-pv-claim
 ---
 apiVersion: extensions/v1beta1
 kind: Deployment
@@ -1064,15 +1066,15 @@ metadata:
   labels:
     component: swip-db-consul
     release: swip-db
-  name: swip-db-consul
+  name: polaris-db-consul
   namespace: ${NAMESPACE}
 spec:
-  replicas: 3
+  replicas: 1
   selector:
     matchLabels:
       component: swip-db-consul
       release: swip-db
-  serviceName: swip-db-consul
+  serviceName: polaris-db-consul
   template:
     metadata:
       labels:
@@ -1080,7 +1082,7 @@ spec:
         component: swip-db-consul
         heritage: Tiller
         release: swip-db
-      name: swip-db-consul
+      name: polaris-db-consul
     spec:
       affinity:
         podAntiAffinity:
@@ -1137,9 +1139,9 @@ spec:
             -http-port=8500
         env:
         - name: INITIAL_CLUSTER_SIZE
-          value: "3"
+          value: "1"
         - name: STATEFULSET_NAME
-          value: swip-db-consul
+          value: polaris-db-consul
         - name: POD_IP
           valueFrom:
             fieldRef:
@@ -1159,7 +1161,7 @@ spec:
             - members
           initialDelaySeconds: 300
           timeoutSeconds: 5
-        name: swip-db-consul
+        name: polaris-db-consul
         ports:
         - containerPort: 8500
           name: http
@@ -1196,7 +1198,7 @@ spec:
       volumes:
       - name: gossip-key
         secret:
-          secretName: swip-db-consul-gossip-key
+          secretName: polaris-db-consul-gossip-key
   updateStrategy:
     type: RollingUpdate
   volumeClaimTemplates:
@@ -1215,7 +1217,7 @@ metadata:
   labels:
     component: swip-db-consul
     release: swip-db
-  name: swip-db-consul-pdb
+  name: polaris-db-consul-pdb
   namespace: ${NAMESPACE}
 spec:
   maxUnavailable: 1
@@ -1226,13 +1228,13 @@ spec:
 apiVersion: policy/v1beta1
 kind: PodDisruptionBudget
 metadata:
-  name: swip-db-vault
+  name: polaris-db-vault
   namespace: ${NAMESPACE}
 spec:
   maxUnavailable: 1
   selector:
     matchLabels:
-      app: vault
+      app: polaris-db-vault
       release: swip-db
 ---
 apiVersion: batch/v1
@@ -1466,7 +1468,7 @@ spec:
         - vault-tls-init
         env:
         - name: VAULT_SERVICE_NAME
-          value: swip-db-vault
+          value: polaris-db-vault
         - name: VAULT_KUBERNETES_NAMESPACE
           value: default
         - name: VAULT_CLIENT_CERTIFICATES
@@ -1525,7 +1527,7 @@ kind: Pod
 metadata:
   annotations:
     helm.sh/hook: test-success
-  name: swip-db-ui-test-2gqxy
+  name: swip-db-ui-test-cf1ob
   namespace: ${NAMESPACE}
 spec:
   containers:
@@ -1557,7 +1559,7 @@ spec:
   restartPolicy: Never
   volumes:
   - configMap:
-      name: swip-db-consul-tests
+      name: polaris-db-consul-tests
     name: tests
   - emptyDir: {}
     name: tools
@@ -1577,7 +1579,7 @@ spec:
     - vault status
     env:
     - name: VAULT_ADDR
-      value: http://swip-db-vault.default:8200
+      value: http://polaris-db-vault.default:8200
     image: vault:0.11.2
     name: swip-db-vault-status-test
   restartPolicy: Never
